### ISSUE TITLE
Not compiling error. 

### ISSUE THREAD

**Issue by fkkcloud** [vanderlin/ofxBox2d#103]
I added Box2D addon to of/addons/

and launched example-Simple.

When I compile.

> clang: warning: -lpthread: 'linker' input unused
> clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)

Did anybody had there issue?

OSX 10.11.3 El Capitan
XCode 7.2.1

Thanks,

**Comment by danomatika** [comment]
The included project files are too old. Use the ProjectGenerator to regenerate them.
