### ISSUE TITLE
Error with a new qtcreator 4.0

### ISSUE THREAD

**Issue by FieryCod** [vanderlin/ofxBox2d#107]
I ve updated the qt creator to new version I mean 4.0 and after this I am receiving the following error.
![zaznaczenie_003](https://cloud.githubusercontent.com/assets/14275210/15394847/5cef9d86-1dd5-11e6-86fb-a20be907192b.png)

I tried to change the following line :
![zaznaczenie_004](https://cloud.githubusercontent.com/assets/14275210/15394867/8313f26e-1dd5-11e6-800a-389d37f92a38.png)

to this: 
![zaznaczenie_005](https://cloud.githubusercontent.com/assets/14275210/15394890/9ffc63ac-1dd5-11e6-8216-5f537885dd0f.png).
After this change the program compiles succesfully but I do not see rectangles in my game.
In old qt creator everything is fine ;(

**Comment by CharlesPL** [comment]
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl rtaudio libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
[notice ] ofxBox2d:: - world created -
/bin/sh: linia 1: 17674 Naruszenie ochrony pamięci   (zrzut pamięci) ./example-Bodies
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:169: polecenia dla obiektu 'run' nie powiodły się
make: *** [run] Błąd 139
I tried as well to build a very simple "example-Bodies" but I could not even run it.

**Comment by CharlesPL** [comment]
I tried to run another example but it gives me only this when I want to create a polygon
ofxBox2dBaseShape:: - must have a valid world.
My version of openframeworks is the that one cloned from git.

**Comment by vanderlin** [comment]
I have replaced the traingle++ lib.
