### ISSUE TITLE
kinematic body?

### ISSUE THREAD

**Issue by hachem28** [vanderlin/ofxBox2d#112]
Are kinematic bodies supported with the ofxBox2d addon? I see comments in the code saying they have no mass like static bodies but with a non-zero velocity. But I see no actual documentation or code on how to use it.
Thanks.

I'm sorry if this is an obvious question or if i posted this in the wrong section. Still new to the scene.

**Comment by vanderlin** [comment]
I not sure I understand the question, maybe refer to the box2d docs. http://box2d.org/manual.pdf
