### ISSUE TITLE
stable branch should remove project files & rename testApp to ofApp

### ISSUE THREAD

**Issue by danomatika** [vanderlin/ofxBox2d#116]
ping @kylemcdonald @bakercp 

This is related to #103.

The current stable branch has a host of project files, many of which may or may not build. I'd suggest removing all project files and add notes on how generate them with the PG. I ran into this with a room full of students today as I assumed it was fixed with my PR last year: https://github.com/vanderlin/ofxBox2d/pull/105

Also, the stable branch examples still use "testApp" instead of "ofApp", so they do not work with the PG. This was also fixed my PR. This means the current state of the "stable" branch is that the included example Xcode projects do not work with the latest stable OF 0.9.8 **AND** the PG chokes since the base app class has the wrong name. Not fun for beginners!

Another thing, the readme still refers to develop and master branches at the bottom. That should probably be removed. I would also remove the develop branch if it is no longer needed.

If needed, I have a set of instructions on how to use the PG for my class examples. We could use this text as a template for updating the readme: https://github.com/danomatika/CreativeCodingExamples#generating-project-files

**Comment by bakercp** [comment]
And I've got another working branch that had most of your suggestions already

https://github.com/bakercp/ofxbox2d

**Comment by bakercp** [comment]
Also, I've basically tell students unless an add-on is in my account and had been tested by me prior to class, it probably won't work (we work from the master branch) :)

**Comment by danomatika** [comment]
The purpose of my PR last year was to fix it. I'm not sure it helps to always have students rely on our own forks. It was a good discussion into how to troubleshoot addons which have issues but my overall point is that something called "stable" should probably be so as opposed to "figure it out beginners". As stated, the solution is pretty simple and I would have done it already if I had commit access.

**Comment by vanderlin** [comment]
fixed with new updates
