### ISSUE TITLE
static polygon shape not working

### ISSUE THREAD

**Issue by sinsynplus** [vanderlin/ofxBox2d#119]
using the provided example-ComplexPolygon and setting density to 0.0 to get static objects the shape disappears.. or seems to introduce a strange offset between collider and drawing..
density 0.0 works as expected for circles and rectangles..

**Comment by vanderlin** [comment]
I was not able to recreate this issue. 

```
poly = make_shared<ofxBox2dPolygon>();    
poly->setPhysics(0, 0, 0);
poly->addTriangle({-100, 100}, {0, -100}, {100, 100});
poly->create(box2d.getWorld());
poly->setPosition(x, y);
```
