### ISSUE TITLE
ofxBox2dEdge allows bodies to travel through it

### ISSUE THREAD

**Issue by RaphiePS** [vanderlin/ofxBox2d#123]
Running the EdgeShape example, I've found the circles and squares can fall right through the edge.

![image](https://user-images.githubusercontent.com/1091375/37933148-3be986da-30ff-11e8-884d-0bf37c5f7df6.png)

 Is this expected behavior, a flaw in Box2D itself, or a bug in ofxBox2d? Thank you!

**Comment by vanderlin** [comment]
Yes - this is just due to the fact that the edge shape is being created each frame. You can try to increase the iterations per frame and see if it helps.
