### ISSUE TITLE
Array of dynamic size causing compiler error in Visual Studio

### ISSUE THREAD

**Issue by corybarr** [vanderlin/ofxBox2d#14]
Compilation under Visual Studio generates these errors:

1>c:\users\coryba\source\openframeworks\of_prerelease_v007_vs2010\of_prerelease_v007_vs2010\addons\ofxbox2d\src\ofxbox2dpolygon.cpp(217): error C2057: expected constant expression
1>c:\users\coryba\source\openframeworks\of_prerelease_v007_vs2010\of_prerelease_v007_vs2010\addons\ofxbox2d\src\ofxbox2dpolygon.cpp(217): error C2466: cannot allocate an array of constant size 0
1>c:\users\coryba\source\openframeworks\of_prerelease_v007_vs2010\of_prerelease_v007_vs2010\addons\ofxbox2d\src\ofxbox2dpolygon.cpp(217): error C2133: 'verts' : unknown size

with the mouseover error of "function call is not allowed in a constant expression"

**Comment by Vamoss** [comment]
This stil happening on the VS2012, because the default version of GCC does not support arrays with variable sizes.

by changing the ofxBox2dPolygonUtils.h:
line 114 to:
vector<int> mk(n);

line 128 to:
simplifyDP( tol, &vt[0], 0, k-1, &mk[0] );
