### ISSUE TITLE
issues compiling in Visual Studio

### ISSUE THREAD

**Issue by cboctor** [vanderlin/ofxBox2d#49]
Main issues with triangle_impl.hpp
First issue defining sys/time.h, renamed to just time.h to fix this, then i get all these errors.

1>dpoint.hpp(634): warning C4244: 'return' : conversion from 'double' to 'float', possible loss of data
1>triangle_impl.hpp(3334): warning C4101: 'k' : unreferenced local variable
1>triangle_impl.hpp(3334): warning C4101: 'workstring' : unreferenced local variable
1>triangle_impl.hpp(12536): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\string.h(105) : see declaration of 'strcpy'
1>triangle_impl.hpp(15374): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(234) : see declaration of 'fopen'
1>triangle_impl.hpp(15784): error C2079: 'tv0' uses undefined struct 'piyush::triangulate::timeval'
1>triangle_impl.hpp(15784): error C2079: 'tv1' uses undefined struct 'piyush::triangulate::timeval'
1>triangle_impl.hpp(15784): error C2079: 'tv2' uses undefined struct 'piyush::triangulate::timeval'
1>triangle_impl.hpp(15784): error C2079: 'tv3' uses undefined struct 'piyush::triangulate::timeval'
1>triangle_impl.hpp(15784): error C2079: 'tv4' uses undefined struct 'piyush::triangulate::timeval'
1>triangle_impl.hpp(15784): error C2079: 'tv5' uses undefined struct 'piyush::triangulate::timeval'
1>triangle_impl.hpp(15784): error C2079: 'tv6' uses undefined struct 'piyush::triangulate::timeval'
1>triangle_impl.hpp(15785): error C2079: 'tz' uses undefined struct 'piyush::triangulate::timezone'
1>triangle_impl.hpp(15789): error C3861: 'gettimeofday': identifier not found
1>triangle_impl.hpp(15810): error C3861: 'gettimeofday': identifier not found
1>triangle_impl.hpp(15837): error C3861: 'gettimeofday': identifier not found
1>triangle_impl.hpp(15843): error C2228: left of '.tv_sec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(15843): error C2228: left of '.tv_sec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(15844): error C2228: left of '.tv_usec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(15844): error C2228: left of '.tv_usec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(15869): error C3861: 'gettimeofday': identifier not found
1>triangle_impl.hpp(15872): error C2228: left of '.tv_sec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(15872): error C2228: left of '.tv_sec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(15873): error C2228: left of '.tv_usec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(15873): error C2228: left of '.tv_usec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(15902): error C3861: 'gettimeofday': identifier not found
1>triangle_impl.hpp(15904): error C2228: left of '.tv_sec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(15904): error C2228: left of '.tv_sec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(15905): error C2228: left of '.tv_usec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(15905): error C2228: left of '.tv_usec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(15918): error C3861: 'gettimeofday': identifier not found
1>triangle_impl.hpp(16065): error C3861: 'gettimeofday': identifier not found
1>triangle_impl.hpp(16067): error C2228: left of '.tv_sec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(16067): error C2228: left of '.tv_sec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(16068): error C2228: left of '.tv_usec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(16068): error C2228: left of '.tv_usec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(16070): error C2228: left of '.tv_sec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(16070): error C2228: left of '.tv_sec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(16071): error C2228: left of '.tv_usec' must have class/struct/union
1>          type is 'int'
1>triangle_impl.hpp(16071): error C2228: left of '.tv_usec' must have class/struct/union
1>          type is 'int'

**Comment by MichealRay** [comment]
Include the <winsock2.h> will work
