### ISSUE TITLE
there are no tags to checkout

### ISSUE THREAD

**Issue by sidestepism** [vanderlin/ofxBox2d#73]
README says that I can get a compatible release by checking out a tag with OF version name, but..

    % git clone git://github.com/vanderlin/ofxBox2d.git
    % cd ofxBox2d
    % git checkout 008
    error: pathspec '008' did not match any file(s) known to git.
    % git tag
    %

If we cannot support older version of OF, we should remove this section from README.

Thanks,

**Comment by fabiantheblind** [comment]
Same problem here.

**Comment by icq4ever** [comment]
same here! any update yet? 
also with oF 0.8.4, add with oFPlugin not work for me.

check this thread.
http://forum.openframeworks.cc/t/ofxbox2d-circle-generation-faild-weird-error/20252

**Comment by kylemcdonald** [comment]
this was a bug in the readme. the `master` branch is compatible with the current OF release (0.8.4) and the `develop` branch tries to stay up to date with OF on GitHub. i've updated the readme to clarify this, and fixed `develop` to be up to date with https://github.com/openframeworks/openFrameworks/commit/c214832ee9a7e1812a249f0f731d620fc8e53000
