### ISSUE TITLE
Assertion failed: LEQ( **(i+1), **i ) in triangulatePolygonWithOutline 

### ISSUE THREAD

**Issue by samubence** [vanderlin/ofxBox2d#79]
triangulatePolygonWithOutline function causes this error in some cases:
Assertion failed: LEQ( *_(i+1), *_i ), file ../Sources/priorityq.c, line 413

by re-enabling size check seems to solve the problem...
/*
float disA  = 5;//ofDist(center.x, center.y, a.x, a.y);
float disB  = 5;//ofDist(center.x, center.y, b.x, b.y);
float disC  = 5;//ofDist(center.x, center.y, c.x, c.y);
*/
float disA  = ofDist(center.x, center.y, a.x, a.y);
float disB  = ofDist(center.x, center.y, b.x, b.y);
float disC  = ofDist(center.x, center.y, c.x, c.y);

**Comment by vanderlin** [comment]
The triangulation has been replaced.
