### ISSUE TITLE
Draw functions not working?

### ISSUE THREAD

**Issue by jorditost** [vanderlin/ofxBox2d#88]
Hi,

I am using the last version of ofxBox2d and it's throwing errors in all draw functions (`ofDrawLine`, `ofDrawCircle`, etc.). I tested it with all 0.8 releases (0.8.0 to 0.8.4).

The errors:

![screen shot 2015-04-17 at 17 24 40](https://cloud.githubusercontent.com/assets/859148/7205030/ad6dac0a-e526-11e4-88d3-1a09f3067704.png)

Do you have any idea about why this is happening?

**Comment by jorditost** [comment]
I tested with the repository version of openFrameworks and is working.

The renaming of ofCircle to ofDrawCircle, etc. is planned for oF 0.9.0:
https://github.com/openframeworks/openFrameworks/pull/3321

Which is the last ofxBox2d commit compatible with oF 0.8.4?

**Comment by kylemcdonald** [comment]
i just fixed this, `master` is now compatible with 0.8.4 and `develop` is compatible with 0.9.0.

**Comment by fabiantheblind** [comment]
:+1:
