### ISSUE TITLE
[QUESTION] singular creation of box2d entities

### ISSUE THREAD

**Issue by lewislepton** [vanderlin/ofxBox2d#89]
this is something i have had major trouble in for some time.

but al i would like to do is create single entities of box2d objects. so rather than having a vector able to create hundreds. i just want to set it for say 1 or 2 without the use of vectors. as if you were to create a character/player with 1, then set others for enemies etc. which if using vector seems a bit much just for 1 thing.
but something like this doesnt seem possible. or at least i have not been able to spot it, even in the examples.

would be groat if you could help. only posting on here since there is no contact on your website

thanks

**Comment by kylemcdonald** [comment]
since this is more of a question than an issue, the forum would be better http://forum.openframeworks.cc/
